#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"). You may
# only use this file in accordance with the terms of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright 2024 Marcel Telka
#

BUILD_STYLE = pkg

WS_TOP= ../../..
include $(WS_TOP)/make-rules/shared-macros.mk

COMPONENT_NAME =		sunray-essential
COMPONENT_VERSION =		5.4
COMPONENT_REVISION =		3
COMPONENT_SUMMARY =		On OI required packages for Sunray Server Software
COMPONENT_PROJECT_URL =		https://www.openindiana.org
COMPONENT_FMRI =		consolidation/srss/$(COMPONENT_NAME)
COMPONENT_CLASSIFICATION =	System/Virtualization

include $(WS_MAKE_RULES)/common.mk

